apiVersion: apps/v1
kind: Deployment
metadata:
  name: leak-maker
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leak-maker
  template:
    metadata:
      labels:
        app: leak-maker
    spec:
      containers:
      - name: leak-maker
        image: k3d-lab-registry.localhost:12345/leak-maker:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 20m
            memory: 10Mi
          requests:
            cpu: 10m
            memory: 10Mi