apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: k3d-leak-maker
spec:
  routes:
    - match: Host(`leak-maker.k3d.lab`)
      kind: Rule
      services:
        - name: leak-maker
          port: 8080