apiVersion: v1
kind: Service
metadata:
  name: leak-maker
  labels:
    app: leak-maker
spec:
  # type: NodePort
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
  selector:
    app: leak-maker