global:
  scrape_interval: 5s
  scrape_timeout: 1s
  evaluation_interval: 5s

scrape_configs:
- job_name: leak-maker
  metrics_path: /metrics
  static_configs:
  - targets: 
    - lab-proxy-nginx:8080